change to meta to possibly l18n oauth
wiki-ai/wikilabels-wikimedia-config pull request #40
Opened 2017-08-01 23:00 UTC by Pix1234

2017-08-01 23:01 UTC, Pix1234 commented
Per bryan davis this should do what we want

2017-08-01 23:03 UTC, Ladsgroup requested changes

2017-08-01 23:03 UTC, Ladsgroup commented on config/00-main.yaml
> +  mw_uri: https://www.meta.wikimedia.org/w/index.php
Besides that I'm not sure if we should do this at all, www.meta.wikimedia.org is wrong, you need to omit www.

2017-08-01 23:50 UTC, adamwight requested changes
We should continue discussion on the task since I don't see agreement to go in the direction taken here. 

Also, small bookkeeping thing so I don't have to use Phabricator search again ;-) : please reference the bug from your commit messages, something like:

Bug: https://phabricator.wikimedia.org/T166472

Thanks!

2017-08-02 19:07 UTC, Pix1234 commented
@adamwight  I meant to let me fix this

2017-08-02 20:36 UTC, merged